### PR TITLE
Exclude directories from classmap for Composer2

### PR DESCRIPTION
**Pull request by golgote**

### CODE REVIEW

**Comment by TheMY3** [comment]
@golgote thank you, but I repeat my question - https://github.com/pear/HTML_QuickForm2/issues/4#issuecomment-819452111

Are you sure that `exclude-from-classmap` should be placed here, not in https://github.com/pear/HTML_Common2?

Errors was with related repository -  https://github.com/pear/HTML_Common2
```
Class HTML_Common2_Concrete located in ./vendor/pear/html_common2/tests/HTML_Common2_Test.php does not comply with psr-0 autoloading standard. Skipping.
Class HTML_Common2_WatchedAttributes located in ./vendor/pear/html_common2/tests/HTML_Common2_Test.php does not comply with psr-0 autoloading standard. Skipping.
Class HTML_Common2_Test located in ./vendor/pear/html_common2/tests/HTML_Common2_Test.php does not comply with psr-0 autoloading standard. Skipping.
Class HTML_Common2_AllTests located in ./vendor/pear/html_common2/tests/AllTests.php does not comply with psr-0 autoloading standard. Skipping.
```

**Comment by golgote** [comment]
Yes, this should **also** be done on html_common2, so you should do a pull request there maybe.

**Comment by sad-spirit** [comment]
@golgote this looks a bit heavy-handed. If I do something along the lines of
```
    "autoload": {
        "psr-0": {
            "HTML_QuickForm2": ""
        },
        "exclude-from-classmap": ["docs/"]
    },
    "autoload-dev": {
        "classmap": ["tests/"]
    }
```
in composer.json then the errors are gone **and** autoloading works for test classes (we aren't using autoloading there as tests should run from pear installation, but still).

**Comment by golgote** [comment]
I haven't tested but I think that you will still get the deprecated warnings if the tests directory is installed because its structure seems to be incompatible with what the autoloaders expect.

**Comment by sad-spirit** [comment]
After a bit of research I ended up with https://github.com/pear/HTML_QuickForm2/commit/ff2be813c9c5e0f69d0ef24bb3db1778ff131fdc and https://github.com/pear/HTML_QuickForm2/commit/b9cc68609802304f850d32724a2b7bdec57bb544

No errors are triggered when generating optimized autoloader either for a git checkout of HTML_QuickForm2 or for a package having HTML_QuickForm2 as a dependency.

**Pull request closed without merging**
